USE mysql;

CREATE DATABASE IF NOT EXISTS MYSQL_DB;

CREATE USER 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';

GRANT ALL ON MYSQL_DB.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD' WITH GRANT OPTION;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'PASS_ROOT';

FLUSH PRIVILEGES;