USE mysql;

CREATE DATABASE IF NOT EXISTS MYSQL_DB;

CREATE USER 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';

GRANT ALL ON MYSQL_DB.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD' WITH GRANT OPTION;

FLUSH PRIVILEGES;